### ISSUE TITLE
Support price as a search operator

### ISSUE THREAD

**Issue by crookedneighbor** [Commander-Spellbook/website-v2#122]
Tricky thing here will be what price do we use? TCGPlayer or Card Kingdom?

`price` and `usd` should both be supported.

```
usd>12.20
usd>=12.34
usd<5
usd<=5
usd:30.12 # equivalent to =
usd=1
```

**Comment by mathematicalninja** [comment]
You could always add in  a "preferred card site" option, possible saved as a cookie.

**Comment by crookedneighbor** [comment]
I think for now, we're going to go with an API like this:

```
# by default, this looks for combos that are less than $5 on cardkingdom
price<5

# overwrite the default vendor and look for cards that are less than $5 on tcgplayer
price<5 vendor:tcgplayer
```

And when we add user accounts, we can have that default vendor be set by the user.
