### ISSUE TITLE
Need Unfinity Ticket symbol support

### ISSUE THREAD

**Issue by thirdpolice** [Commander-Spellbook/website-v2#292]
With the upcoming release of Unfinity, editors need a way to display the ticket symbol (see https://scryfall.com/card/unf/89/scampire for an example).

I will collect feedback from Discord about which letter to use as the code. (We should avoid {T} since that is the tap symbol.)

**Comment by thirdpolice** [comment]
Wizards R&D uses {TK} and Scryfall uses {TIX}. Either of those seem fine to me.

**Comment by crookedneighbor** [comment]
Do you have a link that shows that it’s {TK} officially? Scryfall is only using {TIX} provisionally until they find out what the official plaintext version of the symbol is.

**Comment by thirdpolice** [comment]
That's according to [Mark Rosewater's blog](https://markrosewater.tumblr.com/post/690681014793666560/any-thought-of-what-letter-should-represent-the)

**Comment by ldeluigi** [comment]
![image](https://user-images.githubusercontent.com/44567586/193279270-1227f9c3-d86d-4598-8c2e-004dfea36ad8.png)
from scryfall HTML source
