### ISSUE TITLE
Mana symbol images failing to load sporadically

### ISSUE THREAD

**Issue by thirdpolice** [Commander-Spellbook/website-v2#293]
Mana symbols aren't always loading correctly for all users, especially on the first visit to a page.

Deloo says:
"sometimes this redirects properly and sometimes doesn't
![image](https://user-images.githubusercontent.com/8032571/193250366-d7642d38-1b2b-4085-90a9-9f4cd0580a71.png)
c2.scryfall.com references should be removed from symbols too"

**Comment by ldeluigi** [comment]
c2.scryfall.com references should be removed from symbols too

**Comment by ldeluigi** [comment]
![image](https://user-images.githubusercontent.com/44567586/193250821-a03029ca-6afb-4154-8e56-0a8e436663b0.png)

**Comment by ldeluigi** [comment]
https://github.com/Commander-Spellbook/website-v2/search?q=c1.scryfall.com

**Comment by ldeluigi** [comment]
It seems to be an issue that depends on scryfall-client, based on this:
https://github.com/Commander-Spellbook/website-v2/blob/4a483420f15b4a8eed783915725775d6659df9f9/frontend/components/TextWithMagicSymbol.vue#L108

**Comment by ldeluigi** [comment]
Here you go:
https://github.com/crookedneighbor/scryfall-client/blob/a1363ef05f50ce30c38b0c0244d9b188d67b7fb1/src/index.ts#L46

**Comment by crookedneighbor** [comment]
:wave: Scryfall has their cdn url set incorrectly on the [symbology endpoint](https://api.scryfall.com/symbology?pretty=true) at the moment.

I've alerted them and expect it to be resolved by end of day.

**Comment by crookedneighbor** [comment]
Also, I was already in the process of changing over my strategy for fetching the symbols CDN: https://github.com/crookedneighbor/scryfall-client/pull/39

Just waiting on the upstream issues with Scryfall to resolve before I merge and release it.
