### ISSUE TITLE
Add some query param to combo page that will let you re-run the random combo

### ISSUE THREAD

**Issue by crookedneighbor** [Commander-Spellbook/website-v2#62]
If you get to a combo page via the `/random` route, we could add a `?source=random` query param, which could cause it to display a button to randomize for another combo.

**Comment by CVPhelan** [comment]
I kinda like the idea of having the random combo button permanently in the header so you can always go to a random combo from wherever you are.

**Comment by crookedneighbor** [comment]
That may be the better solve here.

**Comment by CVPhelan** [comment]
I would be happy to work on this once a final decision is made.
