### ISSUE TITLE
Change Combo Heading Title to something better than Combo X

### ISSUE THREAD

**Issue by crookedneighbor** [Commander-Spellbook/website-v2#67]
Some brainstorm options:

![](https://cdn.discordapp.com/attachments/794230947104948235/820317379313401896/Screen_Shot_2021-03-13_at_9.28.14_AM.png)

![](https://cdn.discordapp.com/attachments/794230947104948235/820316497834278932/Screen_Shot_2021-03-13_at_9.24.46_AM.png)

![](https://cdn.discordapp.com/attachments/794230947104948235/820314539777196042/Screen_Shot_2021-03-13_at_9.09.39_AM.png)

![](https://cdn.discordapp.com/attachments/794230947104948235/820314470797672468/Screen_Shot_2021-03-13_at_9.16.42_AM.png)

**Comment by CVPhelan** [comment]
Have we considered allowing aliases for already named combos, like mike and trike, thunian spike, etc? 

Are we against letting people submit names when they submit combos?

ID's may not be pretty, but at the very least they're succinct. we could maybe come up with a code system where we use letters from the color identity and the cards, or establish some kind of primary key and system for the other letters so the combos names dont get super long with six card combos.

options two and three you've mocked up are my favorites. Maybe we do a primary key, so medomai the agless, as well as color identity, and maybe one other distinguishing card? gets tricky when there are multiple combos with 3 of the same cards and only one changing. But something like "Ambassdor Laquatas, Grixis combo with two other cards."

**Comment by crookedneighbor** [comment]
> Have we considered allowing aliases for already named combos, like mike and trike, thunian spike, etc?
> Are we against letting people submit names when they submit combos?

It's just not possible with our existing google sheets system without adding an additional column. This is a long term plan to add as a feature once we move to a SQL database.

> ID's may not be pretty, but at the very least they're succinct. we could maybe come up with a code system where we use letters from the color identity and the cards, or establish some kind of primary key and system for the other letters so the combos names dont get super long with six card combos.

We don't need to worry about this. Once we move to a database, we can let the database create the keys automatically. (and preserve the original key to allow for redirects from the old paths)
