### ISSUE TITLE
Add “buy this combo” links 

### ISSUE THREAD

**Issue by crookedneighbor** [Commander-Spellbook/website-v2#76]
- [ ] secure partnership with tcgplayer/cardkingdom/etc
- [ ] As part of the build process for each combo, look up the price of each card in the combo
- [ ] Add “buy this combo on <vendor> ($<total-price>)” buttons for each partner with an affiliate link

**Comment by CVPhelan** [comment]
I would also like to tie in the tcgplayer api for individual prices of cards in the combo. We could then also aggregate them into a cost of combo box, kinda like how tappedout does it. I would be happy to work on this but would need a little guidance.

**Comment by crookedneighbor** [comment]
Closing as a duplicate of #48
