### ISSUE TITLE
Deck Analyzer

### ISSUE THREAD

**Issue by crookedneighbor** [Commander-Spellbook/website-v2#90]
Finds combos that already exist in deck and suggest combos that are almost in the deck (IE, just missing x cards)

**Comment by CVPhelan** [comment]
Since we are part of EDHrec, we could also utilize the edhrec data of high synergy cards etc, and even possibly utilize the combo feature on edhrec itself to recommend combos for a commander. I know this is a ways off but I would really like to contribute to this.

**Comment by crookedneighbor** [comment]
closed with #326
