### ISSUE TITLE
Pre-fetch the Scryfall Image CDN Links when building the combo page

### ISSUE THREAD

**Issue by crookedneighbor** [Commander-Spellbook/website-v2#95]
This is a flow chart of what our current implementation looks like:

![current](https://user-images.githubusercontent.com/2916945/111725980-077a5000-8836-11eb-9fac-07dc99c371a3.png)

The left side is the stuff that happens pre-deploy, and the right happens when a user visits a combo page.
We're going to have quite a bit of latency here, especially with the combos with lots of cards. For instance, if there are 10 cards, then we're doing 20 concurrent requests to the Scryfall API (one for each card, and one for each art crop). Each of those requests is waiting for Scryfall to look up the card and respond with the redirect to Scryfall's CDN.

Here's what I propose we do instead:

![proposed](https://user-images.githubusercontent.com/2916945/111725971-06492300-8836-11eb-8031-74395e73dd26.png)

As part of a task before the combos are generated, we can [pull down the bulk data from Scryfall](https://scryfall.com/docs/api/bulk-data) and use that to find the particular paths to the images on the Scryfall CDN and use those directly, rather than go through the Scryfall API.

This adds a little complexity to the build process, but should greatly improve the performance of the combo page rendering time.

**Comment by CVPhelan** [comment]
Thanks for taking the time to make these diagrams, and to explain them to me last night. It really helped! The next couple weeks are crazy for me, but once I get through that, and finish the metrics page, I would love to help with this.
